// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPGOXxnjWEHIYJ8aR199R5b4aROydX28Q',
    appId: '1:183943939427:web:fc40f151af1ef6be22bf56',
    messagingSenderId: '183943939427',
    projectId: 'push-c7d8c',
    authDomain: 'push-c7d8c.firebaseapp.com',
    storageBucket: 'push-c7d8c.appspot.com',
    measurementId: 'G-0XZ0QMJGRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWsbjX-_hAOJvLJpos07NRzcfYIEdJoI',
    appId: '1:183943939427:android:c5ff45448b55dd1e22bf56',
    messagingSenderId: '183943939427',
    projectId: 'push-c7d8c',
    storageBucket: 'push-c7d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPfXkDN7D2ISidA_JG_w9DnwWmggnle-k',
    appId: '1:183943939427:ios:1ed32c7ee98a44cb22bf56',
    messagingSenderId: '183943939427',
    projectId: 'push-c7d8c',
    storageBucket: 'push-c7d8c.appspot.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPfXkDN7D2ISidA_JG_w9DnwWmggnle-k',
    appId: '1:183943939427:ios:29d5d36e8018e0f022bf56',
    messagingSenderId: '183943939427',
    projectId: 'push-c7d8c',
    storageBucket: 'push-c7d8c.appspot.com',
    iosBundleId: 'com.example.push.RunnerTests',
  );
}
